package Vista;

/**
 *
 * @author Catalina
 */
public class VistaAdmistradorMedicamentos extends javax.swing.JFrame {

    /**
     * Creates new form VistaAdmistradorMedicamentos
     */
    public VistaAdmistradorMedicamentos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_disponible = new javax.swing.ButtonGroup();
        jp_fondo = new javax.swing.JPanel();
        jp_encabezado = new javax.swing.JPanel();
        lb_titulo = new javax.swing.JLabel();
        lb_codigo_barra = new javax.swing.JLabel();
        txtf_codigo_barra = new javax.swing.JTextField();
        lb_nombre = new javax.swing.JLabel();
        txtf_nombre = new javax.swing.JTextField();
        lb_stock = new javax.swing.JLabel();
        txtf_stock = new javax.swing.JTextField();
        lb_precio = new javax.swing.JLabel();
        txtf_precio = new javax.swing.JTextField();
        lb_tipo_producto = new javax.swing.JLabel();
        cmb_tipo_producto = new javax.swing.JComboBox<>();
        lb_disponible = new javax.swing.JLabel();
        rb_disponible_si = new javax.swing.JRadioButton();
        rb_disponible_no = new javax.swing.JRadioButton();
        lb_fecha_ingreso = new javax.swing.JLabel();
        dtc_fecha_ingreso = new com.toedter.calendar.JDateChooser();
        lb_caracteristicas = new javax.swing.JLabel();
        ckb_caracteristicas = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_productos = new javax.swing.JTable();
        btn_agregar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_fondo.setBackground(new java.awt.Color(255, 255, 255));

        jp_encabezado.setBackground(new java.awt.Color(204, 255, 204));
        jp_encabezado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lb_titulo.setBackground(new java.awt.Color(0, 0, 0));
        lb_titulo.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        lb_titulo.setForeground(new java.awt.Color(0, 0, 0));
        lb_titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/medical_16124038 (1).png"))); // NOI18N
        lb_titulo.setText("Sistema de gestión de productos farmacéuticos");

        javax.swing.GroupLayout jp_encabezadoLayout = new javax.swing.GroupLayout(jp_encabezado);
        jp_encabezado.setLayout(jp_encabezadoLayout);
        jp_encabezadoLayout.setHorizontalGroup(
            jp_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_encabezadoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lb_titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_encabezadoLayout.setVerticalGroup(
            jp_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_encabezadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_titulo)
                .addGap(17, 17, 17))
        );

        lb_codigo_barra.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lb_codigo_barra.setForeground(new java.awt.Color(0, 0, 0));
        lb_codigo_barra.setText("Código de barra:");

        txtf_codigo_barra.setBackground(new java.awt.Color(204, 204, 204));
        txtf_codigo_barra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtf_codigo_barra.setForeground(new java.awt.Color(0, 0, 0));

        lb_nombre.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lb_nombre.setForeground(new java.awt.Color(0, 0, 0));
        lb_nombre.setText("Nombre:");

        txtf_nombre.setBackground(new java.awt.Color(204, 204, 204));
        txtf_nombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtf_nombre.setForeground(new java.awt.Color(0, 0, 0));

        lb_stock.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lb_stock.setForeground(new java.awt.Color(0, 0, 0));
        lb_stock.setText("Stock:");

        txtf_stock.setBackground(new java.awt.Color(204, 204, 204));
        txtf_stock.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtf_stock.setForeground(new java.awt.Color(0, 0, 0));

        lb_precio.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lb_precio.setForeground(new java.awt.Color(0, 0, 0));
        lb_precio.setText("Precio:");

        txtf_precio.setBackground(new java.awt.Color(204, 204, 204));
        txtf_precio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtf_precio.setForeground(new java.awt.Color(0, 0, 0));

        lb_tipo_producto.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lb_tipo_producto.setForeground(new java.awt.Color(0, 0, 0));
        lb_tipo_producto.setText("Tipo de producto:");

        cmb_tipo_producto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmb_tipo_producto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un tipo", "Medicamento", "Vitamina", "Suplemento" }));

        lb_disponible.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lb_disponible.setForeground(new java.awt.Color(0, 0, 0));
        lb_disponible.setText("Disponible:");

        rb_disponible_si.setBackground(new java.awt.Color(255, 255, 255));
        bg_disponible.add(rb_disponible_si);
        rb_disponible_si.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rb_disponible_si.setForeground(new java.awt.Color(0, 0, 0));
        rb_disponible_si.setSelected(true);
        rb_disponible_si.setText("Si");

        rb_disponible_no.setBackground(new java.awt.Color(255, 255, 255));
        bg_disponible.add(rb_disponible_no);
        rb_disponible_no.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rb_disponible_no.setForeground(new java.awt.Color(0, 0, 0));
        rb_disponible_no.setText("No");

        lb_fecha_ingreso.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lb_fecha_ingreso.setForeground(new java.awt.Color(0, 0, 0));
        lb_fecha_ingreso.setText("Fecha de ingreso:");

        dtc_fecha_ingreso.setBackground(new java.awt.Color(204, 204, 204));
        dtc_fecha_ingreso.setForeground(new java.awt.Color(0, 0, 0));
        dtc_fecha_ingreso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lb_caracteristicas.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lb_caracteristicas.setForeground(new java.awt.Color(0, 0, 0));
        lb_caracteristicas.setText("Caracteriticas adicionales:");

        ckb_caracteristicas.setBackground(new java.awt.Color(204, 204, 204));
        ckb_caracteristicas.setForeground(new java.awt.Color(0, 0, 0));
        ckb_caracteristicas.setText("Si");

        tbl_productos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_productos.setForeground(new java.awt.Color(204, 204, 204));
        tbl_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código de barra", "Nombre", "Stock", "Precio", "Tipo", "Disponible", "Fecha de ingreso", "Caracteristicas"
            }
        ));
        tbl_productos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tbl_productos);

        btn_agregar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_agregar.setText("Agregar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        btn_eliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_eliminar.setText("Eliminar");

        btn_modificar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_modificar.setText("Modificar");

        btn_limpiar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_limpiar.setText("Limpiar");

        javax.swing.GroupLayout jp_fondoLayout = new javax.swing.GroupLayout(jp_fondo);
        jp_fondo.setLayout(jp_fondoLayout);
        jp_fondoLayout.setHorizontalGroup(
            jp_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jp_fondoLayout.createSequentialGroup()
                .addGroup(jp_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_fondoLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jp_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_fondoLayout.createSequentialGroup()
                                .addComponent(lb_caracteristicas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ckb_caracteristicas))
                            .addGroup(jp_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jp_fondoLayout.createSequentialGroup()
                                    .addComponent(lb_fecha_ingreso)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dtc_fecha_ingreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jp_fondoLayout.createSequentialGroup()
                                    .addComponent(lb_disponible)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(rb_disponible_si)
                                    .addGap(18, 18, 18)
                                    .addComponent(rb_disponible_no))
                                .addGroup(jp_fondoLayout.createSequentialGroup()
                                    .addComponent(lb_tipo_producto)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cmb_tipo_producto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jp_fondoLayout.createSequentialGroup()
                                    .addComponent(lb_precio)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtf_precio))
                                .addGroup(jp_fondoLayout.createSequentialGroup()
                                    .addComponent(lb_codigo_barra)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtf_codigo_barra, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jp_fondoLayout.createSequentialGroup()
                                    .addComponent(lb_nombre)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtf_nombre))
                                .addGroup(jp_fondoLayout.createSequentialGroup()
                                    .addComponent(lb_stock)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtf_stock))))
                        .addGap(12, 12, 12))
                    .addGroup(jp_fondoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jp_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jp_fondoLayout.createSequentialGroup()
                                .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jp_fondoLayout.setVerticalGroup(
            jp_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_fondoLayout.createSequentialGroup()
                .addComponent(jp_encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jp_fondoLayout.createSequentialGroup()
                        .addGroup(jp_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_codigo_barra)
                            .addComponent(txtf_codigo_barra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_nombre)
                            .addComponent(txtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_stock)
                            .addComponent(txtf_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_precio)
                            .addComponent(txtf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_tipo_producto)
                            .addComponent(cmb_tipo_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_disponible)
                            .addComponent(rb_disponible_si)
                            .addComponent(rb_disponible_no))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_fecha_ingreso)
                            .addComponent(dtc_fecha_ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_caracteristicas)
                            .addComponent(ckb_caracteristicas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_limpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jp_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_agregar)
                            .addComponent(btn_eliminar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_modificar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAdmistradorMedicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAdmistradorMedicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAdmistradorMedicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAdmistradorMedicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAdmistradorMedicamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_disponible;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JCheckBox ckb_caracteristicas;
    private javax.swing.JComboBox<String> cmb_tipo_producto;
    private com.toedter.calendar.JDateChooser dtc_fecha_ingreso;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jp_encabezado;
    private javax.swing.JPanel jp_fondo;
    private javax.swing.JLabel lb_caracteristicas;
    private javax.swing.JLabel lb_codigo_barra;
    private javax.swing.JLabel lb_disponible;
    private javax.swing.JLabel lb_fecha_ingreso;
    private javax.swing.JLabel lb_nombre;
    private javax.swing.JLabel lb_precio;
    private javax.swing.JLabel lb_stock;
    private javax.swing.JLabel lb_tipo_producto;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JRadioButton rb_disponible_no;
    private javax.swing.JRadioButton rb_disponible_si;
    private javax.swing.JTable tbl_productos;
    private javax.swing.JTextField txtf_codigo_barra;
    private javax.swing.JTextField txtf_nombre;
    private javax.swing.JTextField txtf_precio;
    private javax.swing.JTextField txtf_stock;
    // End of variables declaration//GEN-END:variables
}
