/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Catalina
 */
public class VistaFormulario extends javax.swing.JFrame {

    /**
     * Creates new form VistaFormulario
     */
    public VistaFormulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lb_titulo = new javax.swing.JLabel();
        lb_nombre_apellido = new javax.swing.JLabel();
        txtf_primer_nombre = new javax.swing.JTextField();
        lb_primer_nombre = new javax.swing.JLabel();
        txtf_segundo_nombre = new javax.swing.JTextField();
        txtf_apellido = new javax.swing.JTextField();
        lb_segundo_nombre = new javax.swing.JLabel();
        lb_apellido = new javax.swing.JLabel();
        lb_direccion = new javax.swing.JLabel();
        txtf_calle = new javax.swing.JTextField();
        lb_calle = new javax.swing.JLabel();
        txtf_num_calle = new javax.swing.JTextField();
        lb_num_calle = new javax.swing.JLabel();
        txtf_ciudad = new javax.swing.JTextField();
        lb_ciudad = new javax.swing.JLabel();
        txtf_provincia = new javax.swing.JTextField();
        lb_provincia = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        lb_titulo.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        lb_titulo.setForeground(new java.awt.Color(0, 0, 0));
        lb_titulo.setText("Formulario datos personales");

        lb_nombre_apellido.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lb_nombre_apellido.setForeground(new java.awt.Color(0, 0, 0));
        lb_nombre_apellido.setText("Nombre y apellido:");

        txtf_primer_nombre.setBackground(new java.awt.Color(255, 255, 255));
        txtf_primer_nombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtf_primer_nombre.setForeground(new java.awt.Color(0, 0, 0));
        txtf_primer_nombre.setToolTipText("");

        lb_primer_nombre.setForeground(new java.awt.Color(0, 0, 0));
        lb_primer_nombre.setText("Primer nombre");

        txtf_segundo_nombre.setBackground(new java.awt.Color(255, 255, 255));
        txtf_segundo_nombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtf_segundo_nombre.setForeground(new java.awt.Color(0, 0, 0));
        txtf_segundo_nombre.setToolTipText("");

        txtf_apellido.setBackground(new java.awt.Color(255, 255, 255));
        txtf_apellido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtf_apellido.setForeground(new java.awt.Color(0, 0, 0));
        txtf_apellido.setToolTipText("");

        lb_segundo_nombre.setForeground(new java.awt.Color(0, 0, 0));
        lb_segundo_nombre.setText("Segundo nombre");

        lb_apellido.setForeground(new java.awt.Color(0, 0, 0));
        lb_apellido.setText("Apellido");

        lb_direccion.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lb_direccion.setForeground(new java.awt.Color(0, 0, 0));
        lb_direccion.setText("Dirección:");

        txtf_calle.setBackground(new java.awt.Color(255, 255, 255));
        txtf_calle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtf_calle.setForeground(new java.awt.Color(0, 0, 0));
        txtf_calle.setToolTipText("");

        lb_calle.setForeground(new java.awt.Color(0, 0, 0));
        lb_calle.setText("Calle");

        txtf_num_calle.setBackground(new java.awt.Color(255, 255, 255));
        txtf_num_calle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtf_num_calle.setForeground(new java.awt.Color(0, 0, 0));
        txtf_num_calle.setToolTipText("");

        lb_num_calle.setForeground(new java.awt.Color(0, 0, 0));
        lb_num_calle.setText("Número");

        txtf_ciudad.setBackground(new java.awt.Color(255, 255, 255));
        txtf_ciudad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtf_ciudad.setForeground(new java.awt.Color(0, 0, 0));
        txtf_ciudad.setToolTipText("");

        lb_ciudad.setForeground(new java.awt.Color(0, 0, 0));
        lb_ciudad.setText("Ciudad");

        txtf_provincia.setBackground(new java.awt.Color(255, 255, 255));
        txtf_provincia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtf_provincia.setForeground(new java.awt.Color(0, 0, 0));
        txtf_provincia.setToolTipText("");

        lb_provincia.setForeground(new java.awt.Color(0, 0, 0));
        lb_provincia.setText("Provincia");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_direccion)
                    .addComponent(lb_nombre_apellido)
                    .addComponent(lb_titulo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtf_calle, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lb_primer_nombre)
                                        .addComponent(txtf_primer_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtf_segundo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lb_segundo_nombre))))
                            .addComponent(lb_calle))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lb_num_calle)
                            .addComponent(txtf_apellido, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(lb_apellido)
                            .addComponent(txtf_num_calle)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtf_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_ciudad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_provincia)
                            .addComponent(txtf_provincia, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtf_apellido, txtf_primer_nombre, txtf_segundo_nombre});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lb_titulo)
                .addGap(18, 18, 18)
                .addComponent(lb_nombre_apellido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtf_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtf_segundo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtf_primer_nombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_primer_nombre)
                    .addComponent(lb_segundo_nombre)
                    .addComponent(lb_apellido))
                .addGap(18, 18, 18)
                .addComponent(lb_direccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtf_num_calle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtf_calle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_calle)
                    .addComponent(lb_num_calle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtf_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtf_provincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_ciudad)
                    .addComponent(lb_provincia))
                .addContainerGap(415, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtf_apellido, txtf_segundo_nombre});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaFormulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lb_apellido;
    private javax.swing.JLabel lb_calle;
    private javax.swing.JLabel lb_ciudad;
    private javax.swing.JLabel lb_direccion;
    private javax.swing.JLabel lb_nombre_apellido;
    private javax.swing.JLabel lb_num_calle;
    private javax.swing.JLabel lb_primer_nombre;
    private javax.swing.JLabel lb_provincia;
    private javax.swing.JLabel lb_segundo_nombre;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JTextField txtf_apellido;
    private javax.swing.JTextField txtf_calle;
    private javax.swing.JTextField txtf_ciudad;
    private javax.swing.JTextField txtf_num_calle;
    private javax.swing.JTextField txtf_primer_nombre;
    private javax.swing.JTextField txtf_provincia;
    private javax.swing.JTextField txtf_segundo_nombre;
    // End of variables declaration//GEN-END:variables
}
